# Site Configuration
timezone: Africa/Johannesburg

# Basic Info
title: Incomplete Developer
tagline: Modern Software Development (aahh that would mean AI, right?)
description: >-
  A developer wannable who is very happy to be eating banana but pretends to be knowledgeable about software development. I am a fruit eater with a passion for learning and sharing knowledge. I write about my experiences and insights in the world of software development, hoping to inspire and help others on their own journeys.

url: "https://mpholoane-bapela.github.io"

github:
  username: mpholoane-bapela

social:
  name: Mpholoane Bapela
  email:
  links:
    - https://github.com/mpholoane-bapela
    - https://www.linkedin.com/in/mpholoane-bapela-3349146a
    - https://www.youtube.com/@IncompleteDeveloper
    - https://www.upwork.com/freelancers/~011db411a046eb1c2a?mp_source=share

avatar: /assets/img/avatar.png

# Theme mode: [light|dark]
theme_mode:

toc: true

comments:
  active:

paginate: 10

# Build settings
theme: jekyll-theme-chirpy
